apiVersion: v1
kind: ConfigMap
metadata:
  name: event-booking-config
  namespace: onlineeventbookingabdulwasay
data:
  DATABASE_HOST: "database"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "eventMgmt"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "booking_notifications"
  USER_SERVICE_URL: "http://user-service:3000"
  BOOKING_SERVICE_URL: "http://booking-service:3001"
  EVENT_SERVICE_URL: "http://event-service:3002"
