apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.secrets.databaseUser | b64enc }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc }}
  RABBITMQ_USER: {{ .Values.secrets.rabbitmqUser | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | b64enc }}
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc }} 