{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: service-{{ .name }}
spec:
  type: ClusterIP
  selector:
    app: service-{{ .name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
---
{{- end }} 