{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ .name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
---
{{- end }} 
