global:
  imagePullPolicy: IfNotPresent

gateway:
  image: gateway:latest
  replicaCount: 1
  servicePort: 8080

user:
  image: user-service:latest
  replicaCount: 1
  servicePort: 3000

event:
  image: event-service:latest
  replicaCount: 1
  servicePort: 3002

booking:
  image: booking-service:latest
  replicaCount: 1
  servicePort: 3001

notification:
  image: notification-service:latest
  replicaCount: 1
  servicePort: 3003

frontend:
  image: frontend-service:latest
  replicaCount: 1
  servicePort: 80

postgres:
  image: postgres:15
  servicePort: 5432
  user: postgres
  password: postgres
  db: eventdb

rabbitmq:
  image: rabbitmq:3-management
  servicePort: 5672
  user: guest
  password: guest

ingress:
  enabled: true
  host: eventbooking.local