name: Terraform & Ansible CI

on:
  push:
    paths:
      - 'infrastructure/terraform/**'
      - 'infrastructure/ansible/**'
      - '.github/workflows/infra-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SSH key pair
        run: |
          ssh-keygen -t rsa -b 2048 -f infrastructure/terraform/id_rsa -N ""
      - name: Set correct permissions for private key
        run: chmod 600 infrastructure/terraform/id_rsa

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: infrastructure/terraform
        run: terraform apply -auto-approve -var 'ssh_public_key_path=id_rsa.pub'

      - name: Get EC2 Public IP from Terraform Output
        id: tf_output
        working-directory: infrastructure/terraform
        run: |
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      - name: Generate Ansible Inventory
        working-directory: infrastructure/ansible
        run: |
          echo "all:" > inventory.yml
          echo "  hosts:" >> inventory.yml
          echo "    kubernetes_master:" >> inventory.yml
          echo "      ansible_host: ${{ env.EC2_IP }}" >> inventory.yml
          echo "      ansible_user: ubuntu" >> inventory.yml
          echo "      ansible_ssh_private_key_file: ../terraform/id_rsa" >> inventory.yml
          echo "      ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" >> inventory.yml

      - name: Set up Python & Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible

      - name: Run Ansible Playbook
        working-directory: infrastructure/ansible
        run: ansible-playbook -i inventory.yml kubernetes-setup.yml
